services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/app/.env
    volumes:
      - ./backend/app/data:/app/data
